import { SERVICE_CATALOG } from '@/lib/services';

interface GlossaryEntry {
  slug: string;
  glyph: string;
  accent: string;
  name_en: string;
  name_ar: string;
  name_fr: string;
  history_en: string;
  history_ar: string;
  history_fr: string;
  usage_en: string;
  usage_ar: string;
  usage_fr: string;
  example_en: string;
  example_ar: string;
  example_fr: string;
}

const GLOSSARY: GlossaryEntry[] = [
  {
    slug: 'shadow-profiler', glyph: '\u263D', accent: '#5d4037',
    name_en: 'Shadow Profiler', name_ar: 'محلل الظل', name_fr: 'Profilage de l\u2019Ombre',
    history_en: 'Rooted in Jungian depth psychology, the Shadow is the disowned sum of traits a person refuses to acknowledge. Integration is the act of reclaiming these fragments consciously.',
    history_ar: 'متأصّل في علم النفس اليونغي العميق. الظل هو مجموع السمات المُتنكَّر منها. الدمج هو استعادة هذه الأجزاء بوعي.',
    history_fr: 'Enraciné dans la psychologie des profondeurs de Jung, l\u2019Ombre est la somme des traits désavoués. L\u2019intération les reclaim consciemment.',
    usage_en: 'Answer five prompts honestly. The profiler returns a reflection for each, mapping the disowned fragment.',
    usage_ar: 'أجب عن خمسة أسئلة بصدق. يُعيد المحلل تأملاً لكل إجابة، يرسم الجزء المُتنكَّر منه.',
    usage_fr: 'Répondez honnêtement à cinq invites. Le profilage renvoie une réflexion pour chacune.',
    example_en: 'Prompt: "Whose approval still governs your choices?" Reflection: "The approval you seek is the throne you have abdicated."',
    example_ar: 'سؤال: «من يتحكّم قبوله بخياراتك؟» تأمل: «القبول الذي تطلبه هو العرش الذي تنازلت عنه.»',
    example_fr: 'Invite : « L\u2019approbation de qui gouverne vos choix ? » Réflexion : « Le trône abdiqué. »',
  },
  {
    slug: 'al-zanati-geomancy', glyph: '\u25CF', accent: '#a1887f',
    name_en: 'Al-Zanati Geomancy', name_ar: 'الرمل الزناتي', name_fr: 'Géomancie Al-Zanati',
    history_en: 'A binary divination art of the desert, attributed to the Zanati masters. Sixteen "mothers" are generated by rows of one or two dots, each a geomantic figure with its own meaning.',
    history_ar: 'فن عرافة صحراوي ثنائي يُنسب إلى أساتذة الزناتة. تُولَّد ست عشرة «أمًّا» بصفوف من نقطة أو نقطتين، لكل منها معنى.',
    history_fr: 'Art divinatoire binaire du désert, attribué aux maîtres Zanati. Seize « mères » sont générées par rangées de un ou deux points.',
    usage_en: 'Cast the sand. Four rows of binary dots form one of the sixteen figures. Read its name and current.',
    usage_ar: 'ارمِ الرمل. أربعة صفوف من النقاط الثنائية تكوّن إحدى عشرة شكلاً. اقرأ اسمها وتيارها.',
    usage_fr: 'Lancez le sable. Quatre rangées binaires forment l\u2019une des seize figures.',
    example_en: 'Cast yields [1,2,1,2] → "Conjunctio" — union, meeting, the joining of currents.',
    example_ar: 'الرمي يعطي [١،٢،١،٢] ← «اجتماع» — اتحاد، لقاء، التقاء التيارات.',
    example_fr: 'Le jet donne [1,2,1,2] → « Conjunctio » — union, rencontre des courants.',
  },
  {
    slug: 'luciferian-tarot', glyph: '\u2727', accent: '#8d6e63',
    name_en: 'Luciferian Tarot Oracle', name_ar: 'تاروت اللوسيفيري', name_fr: 'Oracle Tarot Luciférien',
    history_en: 'A night-side reading of the 22 trumps through the Qliphothic tree — the shadow-mirror of the Kabbalistic sephiroth. Each card is a current of the unseen.',
    history_ar: 'قراءة ليلية لاثنتين وعشرين ورقة عبر شجرة القليفوت — المرآة الظلية للسفيروت القبّالي. كل ورقة تيارٌ من الخفي.',
    history_fr: 'Lecture nocturne des 22 atouts via l\u2019arbre Qliphothique — le miroir-ombre des Sephiroth.',
    usage_en: 'Draw one card. It flips to reveal a glyph, name, and meaning from the night-side deck.',
    usage_ar: 'اسحب ورقة. تنكشف لتُظهر رمزًا واسمًا ومعنى من المجموعة الليلية.',
    usage_fr: 'Tirez une carte. Elle se retourne pour révéler un glyphe, un nom et un sens.',
    example_en: 'Draw: "The High Priestess" — intuition, the veiled, the night-side.',
    example_ar: 'السحب: «الكاهنة العليا» — الحدس، المحجوب، الجانب الليلي.',
    example_fr: 'Tirage : « La Grande Prêtresse » — intuition, le voilé, le côté nocturne.',
  },
  {
    slug: 'taoist-shift', glyph: '\u262F', accent: '#4a6b3a',
    name_en: 'Taoist Shift Balancer', name_ar: 'موازن التاو', name_fr: 'Équilibrateur Taoïste',
    history_en: 'From the Five Elements (Wu Xing) of Taoist alchemy — Wood, Fire, Earth, Metal, Water. The balance of elements reveals the Yin/Yang current of the moment.',
    history_ar: 'من العناصر الخمسة (وو شينغ) في الخيمياء الطاوية — خشب، نار، أرض، معدن، ماء. توازن العناصر يكشف تيار اليين/اليانغ.',
    history_fr: 'Des Cinq Éléments (Wu Xing) de l\u2019alchimie taoïste — Bois, Feu, Terre, Métal, Eau.',
    usage_en: 'Adjust the five elements. The engine computes whether Yin, Yang, or the balanced middle path prevails.',
    usage_ar: 'اضبط العناصر الخمسة. يحسب المحرّك هل يسود اليين أو اليانغ أو الطريق الأوسط.',
    usage_fr: 'Ajustez les cinq éléments. Le moteur calcule Yin, Yang ou la voie médiane.',
    example_en: 'All elements at 2 → total 10 → "Balanced · 中" — act from stillness.',
    example_ar: 'كل العناصر عند ٢ ← المجموع ١٠ ← «متوازن · 中» — اعمل من السكون.',
    example_fr: 'Tous à 2 → total 10 → « Équilibré · 中 » — agir depuis le calme.',
  },
  {
    slug: 'kabbalistic-jafr', glyph: '\u05D0', accent: '#b8860b',
    name_en: 'Kabbalistic & Jafr Numerology', name_ar: 'علم الحروف والجفر', name_fr: 'Numérologie Kabbalistique & Jafr',
    history_en: 'The Abjad (Jafr) system assigns numeric values to Arabic letters; the Kabbalistic tradition does the same for Hebrew. A name reduces to a root number with a meaning.',
    history_ar: 'نظام الأبجد (الجفر) يُسند قيمًا عددية للحروف العربية؛ والقبّالية تفعل المثل للعبرية. يُختزل الاسم إلى عدد جذر بمعنى.',
    history_fr: 'Le système Abjad (Jafr) attribue des valeurs aux lettres arabes ; la Kabbale fait de même pour l\u2019hébreu.',
    usage_en: 'Enter a name or word (Arabic or Latin). The Abjad value is computed and reduced to a root number.',
    usage_ar: 'أدخل اسمًا أو كلمة (عربي أو لاتيني). تُحسب قيمة الأبجد وتُختزل إلى عدد جذر.',
    usage_fr: 'Entrez un nom (arabe ou latin). La valeur Abjad est calculée et réduite.',
    example_en: '"علي" → 110 → reduced 2 → "Duality, reflection, the pair."',
    example_ar: '«علي» ← ١١٠ ← مختزل ٢ ← «الاثنينية، الانعكاس، الزوج».',
    example_fr: '« Ali » → 110 → réduit 2 → « Dualité, réflexion, la paire. »',
  },
  {
    slug: 'dream-necromancer', glyph: '\u2742', accent: '#8b3a2e',
    name_en: 'Dream Necromancer', name_ar: 'مفسّر الأحلام', name_fr: 'Nécromancien des Rêves',
    history_en: 'Ancient oneiromancy held that dreams are crossings — the soul speaking in signs. The necromancer surfaces a sign from the ancient glossary for each dream.',
    history_ar: 'اعتبر علم تفسير الأحلام القديم أن الأحلام معابر — تتكلم النفس بالعلامات. يُظهر المفسّر علامة من المعجم القديم لكل حلم.',
    history_fr: 'L\u2019oniromancie ancienne tenait les rêves pour des traversées — l\u2019âme parlant en signes.',
    usage_en: 'Inscribe your dream. The necromancer surfaces a sign and its meaning.',
    usage_ar: 'سجّل حلمك. يُظهر المفسّر علامة ومعناها.',
    usage_fr: 'Inscrivez votre rêve. Le nécromancien fait émerger un signe et son sens.',
    example_en: 'Dream of water → sign "Water" — emotion, the unconscious current.',
    example_ar: 'حلم بالماء ← علامة «ماء» — العاطفة، التيار اللاواعي.',
    example_fr: 'Rêve d\u2019eau → signe « Eau » — émotion, le courant inconscient.',
  },
  {
    slug: 'ritual-alchemy', glyph: '\u2725', accent: '#9a6f08',
    name_en: 'Ritual Alchemy Engine', name_ar: 'محرّك الخيمياء الطقسي', name_fr: 'Moteur d\u2019Alchimie Rituelle',
    history_en: 'Talismans in the Western esoteric tradition are geometric vessels of intent — a polygon, a letter, a name. This engine synthesizes one on the device as a temporary SVG.',
    history_ar: 'التعاويذ في التقليد الباطني الغربي أوعية هندسية للقصد — مضلّع، حرف، اسم. يخلّق هذا المحرّك واحدًا على جهازك كـ SVG مؤقت.',
    history_fr: 'Les talismans de la tradition ésotérique occidentale sont des vaisseaux géométriques d\u2019intent.',
    usage_en: 'Choose an intent, synthesize. A unique talisman renders as a Base64 SVG you may download. Nothing is stored.',
    usage_ar: 'اختر قصدًا، خلّق. يُرسَم تعويذة فريدة كـ SVG بصيغة Base64 يمكنك تنزيلها. لا يُخزَّن شيء.',
    usage_fr: 'Choisissez une intention, synthétisez. Un talisman unique s\u2019affiche en SVG Base64 téléchargeable.',
    example_en: 'Intent "Protection", seed 42891 → a heptagon with the letter ג and the word PROTECTION.',
    example_ar: 'قصد «حماية»، بذرة ٤٢٨٩١ ← مضلّع سباعي بالحرف ג وكلمة PROTECTION.',
    example_fr: 'Intention « Protection » → heptagone avec la lettre ג et le mot PROTECTION.',
  },
  {
    slug: 'bio-energy-synastry', glyph: '\u269B', accent: '#a1887f',
    name_en: 'Bio-Energy Synastry', name_ar: 'التوافق الطاقي', name_fr: 'Synastrie Bio-Énergétique',
    history_en: 'Synastry compares two charts by elemental resonance. Fire-Air and Earth-Water pairings flow; same-element bonds are strongest; cross-polarity creates growth through friction.',
    history_ar: 'يقارن التوافق برسمين بالرنين العنصري. أزواج النار-الهواء والأرض-الماء تجري؛ روابط العنصر نفسه الأقوى؛ والقطبية المتقاطعة تنشئ نموًّا بالاحتكاك.',
    history_fr: 'La synastrie compare deux thèmes par résonance élémentaire.',
    usage_en: 'Enter two zodiac signs. The engine returns a resonance score and a reading.',
    usage_ar: 'أدخل برجين. يُعيد المحرّك نسبة رنين وقراءة.',
    usage_fr: 'Entrez deux signes. Le moteur renvoie un score de résonance et une lecture.',
    example_en: 'Aries + Leo → 90%+ (same element, Fire) — "A strong current."',
    example_ar: 'الحمل + الأسد ← ٩٠٪+ (نفس العنصر، نار) — «تيار قوي».',
    example_fr: 'Bélier + Lion → 90%+ (même élément, Feu) — « un fort courant ».',
  },
  {
    slug: 'planetary-transit', glyph: '\u2609', accent: '#d4af37',
    name_en: 'Planetary Transit Guide', name_ar: 'دليل العبور الكوكبي', name_fr: 'Guide des Transits Planétaires',
    history_en: 'The 28 lunar mansions (Manazil al-Qamar) of the Arabic tradition track the Moon through the zodiac. Each mansion has a theme and a ruling planet for the day.',
    history_ar: 'المنازل القمرية الثمانية والعشرون (منازل القمر) في التقليد العربي تتتبع القمر في البرج. لكل منزل موضوع وكوكب حاكم لليوم.',
    history_fr: 'Les 28 mansions lunaires (Manazil al-Qamar) suivent la Lune à travers le zodiaque.',
    usage_en: 'The guide computes today\'s lunar mansion and ruling planet from the current date.',
    usage_ar: 'يحسب الدليل منزل القمر الحاكم وكوكبه من التاريخ الحالي.',
    usage_fr: 'Le guide calcule la mansion lunaire et la planète régente du jour.',
    example_en: 'On a given day → Mansion 4 "Al-Dabaran" — persistence, the follower; ruling planet Mars.',
    example_ar: 'في يوم ما ← المنزل ٤ «الدبران» — المثابرة، التابع؛ الكوكب الحاكم المريخ.',
    example_fr: 'Un jour donné → Mansion 4 « Al-Dabaran » — persistance ; planète Mars.',
  },
  {
    slug: 'sovereign-guard', glyph: '\u2726', accent: '#3e2723',
    name_en: 'The Sovereign Guard Engine', name_ar: 'محرّك الحارس السيادي', name_fr: 'Moteur de la Garde Souveraine',
    history_en: 'The engagement wheel — a 30-second ritual that surfaces a free daily spin and a behavioral astrological warning, binding the visitor to the codex each day.',
    history_ar: 'عجلة التفاعل — طقس كل ٣٠ ثانية يُظهر دورانًا يوميًّا مجانيًّا وتحذيرًا فلكيًّا سلوكيًّا، يربط الزائر بالمدوّنة كل يوم.',
    history_fr: 'La roue d\u2019engagement — un rituel de 30 secondes offrant un tour gratuit quotidien et un avertissement astrologique comportemental.',
    usage_en: 'Begin the 30-second watch. At zero, the Wheel of Destiny rises with one free daily spin.',
    usage_ar: 'ابدأ المراقبة لـ ٣٠ ثانية. عند الصفر، تُرتفع عجلة القدر بدوران يومي مجاني.',
    usage_fr: 'Lancez la garde de 30 secondes. À zéro, la Roue du Destin s\u2019élève avec un tour gratuit.',
    example_en: 'Spin lands on "Tarot" → "A Qliphothic echo from the night-side asks for shadow integration."',
    example_ar: 'الدوران يستقر على «تاروت» ← «صدى قليفوتي من الجانب الليلي يطلب دمج الظل».',
    example_fr: 'Le tour atterrit sur « Tarot » → « un écho Qliphothique demande l\u2019intégration de l\u2019Ombre ».',
  },
];

export default function GlossaryPage() {
  return (
    <>
      <main className="mx-auto max-w-5xl px-4 pt-10 pb-16">
        <div className="text-center">
          <div className="gold-text text-xs uppercase tracking-[0.35em] mb-2">Onboarding Directory</div>
          <h1 className="ink-heading text-4xl md:text-5xl font-semibold" style={{ fontFamily: 'var(--font-display), serif' }}>
            The Glossary of the Ten Portals
          </h1>
          <p className="mt-3 max-w-2xl mx-auto" style={{ color: 'var(--ink-soft)' }}>
            دليل المصطلحات · Le glossaire des dix portails. History, usage, and symbolic examples — in Arabic, English, and French.
          </p>
        </div>

        <div className="ornament-divider my-10"><span className="text-base">{'\u2767'}</span></div>

        <div className="space-y-6">
          {GLOSSARY.map((g, i) => (
            <article key={g.slug} className="parchment-surface parchment-edge rounded-xl p-6 animate-rise" style={{ animationDelay: `${i * 40}ms` }}>
              <div className="flex items-start gap-4">
                <span className="text-4xl seal-shadow" style={{ color: g.accent }}>{g.glyph}</span>
                <div className="flex-1">
                  <div className="flex items-baseline gap-2 flex-wrap">
                    <h2 className="ink-heading text-2xl font-semibold" style={{ fontFamily: 'var(--font-display), serif' }}>{g.name_en}</h2>
                    <span style={{ color: 'var(--ink-muted)' }} dir="rtl">{g.name_ar}</span>
                    <span style={{ color: 'var(--ink-muted)' }}>· {g.name_fr}</span>
                  </div>

                  <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
                    <GlossaryBlock title="History · التاريخ · Histoire" ar={g.history_ar} en={g.history_en} fr={g.history_fr} />
                    <GlossaryBlock title="Usage · الاستعمال · Usage" ar={g.usage_ar} en={g.usage_en} fr={g.usage_fr} />
                    <GlossaryBlock title="Example · مثال · Exemple" ar={g.example_ar} en={g.example_en} fr={g.example_fr} />
                  </div>
                </div>
              </div>
            </article>
          ))}
        </div>
      </main>
    </>
  );
}

function GlossaryBlock({ title, en, ar, fr }: { title: string; en: string; ar: string; fr: string }) {
  return (
    <div className="rounded-lg p-3" style={{ background: 'rgba(253, 248, 233, 0.5)', border: '1px solid var(--parchment-400)' }}>
      <div className="gold-text text-[10px] uppercase tracking-[0.2em] mb-2">{title}</div>
      <p className="text-sm" style={{ color: 'var(--ink)' }}>{en}</p>
      <p className="text-sm mt-2" style={{ color: 'var(--ink-soft)' }} dir="rtl">{ar}</p>
      <p className="text-sm mt-2 italic" style={{ color: 'var(--ink-soft)' }}>{fr}</p>
    </div>
  );
}
